runtime: python37
instance_class: F4_1G
handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /manifest\.json
  static_files: static/manifest.json
  upload: static/manifest\.json
- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon\.png
- url: /android-chrome-192x192\.png
  static_files: static/android-chrome-192x192.png
  upload: static/android-chrome-192x192\.png
- url: /android-chrome-512x512\.png
  static_files: static/android-chrome-512x512.png
  upload: static/android-chrome-512x512\.png
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
