runtime: python37
instance_class: F4_1G
handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
